# Generated by Django 4.2.29 on 2026-03-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_service_duration_minutes_alter_service_price'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['appointment_date', 'start_time'], name='core_bookin_appoint_d76ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'appointment_date'], name='core_bookin_status_57f113_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['service', 'appointment_date'], name='core_bookin_service_c4b946_idx'),
        ),
    ]
